# Configuration Settings for ZED-F9P device
debug: 1                    # Range 0-4 (0 means no debug statements will print)
device: /dev/ttyGNSS
frame_id: gps
uart1:
    baudrate: 38400
config_on_startup: false

publish:
    all: true
    nmea: true
    use_ros_time: false
